apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-api-ingress
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: openeuler-api
    name: openeuler-external
  project: openeuler
  source:
    path: applications/api-ingress
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true