apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-compass-ci
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: compass-ci
    name: openeuler-external
  project: openeuler
  source:
    path: applications/compass-ci
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
