apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: openeuler-hk-cve-manager-analysis
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: cve-manager
    server: openeuler-external
  project: openeuler
  source:
    path: applications/cve-manager-analysis
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
  info:
    description: cve manager analysis
    owner: xiaojianghui
    owner-email: xiaojianghui@huawei.com
    community: openeuler
    community-owner: caozhi
