apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-cve
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: cve
    name: openeuler-external
  project: openeuler
  source:
    path: applications/cve
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false