apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-cn-north4-lts-dailybuild
  namespace: argocd
  labels:
    community: openeuler-cn-north4
spec:
  destination:
    namespace: dailybuild-lts
    name: openeuler-cn-north4
  project: openeuler
  source:
    path: applications/repo-dailybuild-lts
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
