apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-dailybuild-ingress
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: dailybuild
    name: openeuler-external
  project: openeuler
  source:
    path: applications/hk-dailybuild-ingress
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
