apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-cn-north4-jenkins-2-slave
  namespace: argocd
  labels:
    community: openeuler-cn-north4
spec:
  destination:
    namespace: jenkins
    name: openeuler-cn-north4
  project: openeuler
  source:
    path: applications/jenkins-slave-cn-north4
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true