apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openlookeng-tryme-test-ingress
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: openlookeng-tryme-test
    name: openeuler-external
  project: openeuler
  source:
    path: applications/openlookeng-tryme-test
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
