apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-patch-tracking
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: patch-tracking
    name: openeuler-external
  project: openeuler
  source:
    path: applications/patch-tracking
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
