apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-repo
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: repo-mirror
    name: openeuler-external
  project: openeuler
  source:
    path: applications/repo-hk
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD

