apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-website-v2
  namespace: argocd
  labels:
    community: openeuler-hk
  annotations:
    recipients.argocd-notifications.argoproj.io: email:zhengyuhang@huawei.com
spec:
  destination:
    namespace: website-v2
    name: openeuler-external
  project: openeuler
  source:
    path: applications/openeuler-website-v2
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
  syncPolicy:
