apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-website-backup
  namespace: argocd
  labels:
    community: openeuler-singapore
spec:
  destination:
    namespace: website-v2
    server: https://119.8.174.163:5443 
  project: openeuler
  source:
    path: applications/openeuler-website-backup
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
