apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: cert-manager
    name: openeuler-external
  project: infra-common
  source:
    path: common-applications/control/cert-manager-legacy
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
