apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-ingress
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: ingress-nginx
    name: openeuler-external
  project: infra-common
  source:
    path: common-applications/openeuler-hk/ingress
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
