apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-secret-manager
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: secrets-manager
    name: openeuler-external
  project: infra-common
  source:
    path: common-applications/control/secret-manager
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/scope
        - /status
