apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-cn-north1-cert-fluentd
  namespace: argocd
  labels:
    community: mindspore-cn-north1
spec:
  destination:
    namespace: kube-system
    name: mindspore-external
  project: infra-common
  source:
    path: common-applications/control/fluentd
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
