apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-cn-north1-ingress
  namespace: argocd
  labels:
    community: mindspore-cn-north1
spec:
  destination:
    namespace: ingress-nginx
    name: mindspore-external
  project: infra-common
  source:
    path: common-applications/mindspore-cn-north1/ingress
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
