apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: om-ingress
  namespace: argocd
  labels:
    community: os-infra
spec:
  destination:
    namespace: ingress-nginx
    server: https://119.8.126.189:5443
  project: infra-common
  source:
    path: common-applications/om/ingress
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
