apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openlookeng-cla-om
  namespace: argocd
  labels:
    community: os-infra
spec:
  destination:
    namespace: openlookeng-om
    name: openlookeng-external
  project: infra-common
  source:
    path: common-applications/om/om-collect/cla/openlookeng
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
