apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-cla-om
  namespace: argocd
  labels:
    community: os-infra
spec:
  destination:
    namespace: mindspore-om
    name: cn-north-4-x86-external
  project: infra-common
  source:
    path: common-applications/om/om-collect/cla/mindspore
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
