apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-cla-om
  namespace: argocd
  labels:
    community: os-infra
spec:
  destination:
    namespace: openeuler-om
    name: openeuler-external
  project: infra-common
  source:
    path: common-applications/om/om-collect/cla/openeuler
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
