apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-cla-test
  namespace: argocd
  labels:
    community: os-infra
spec:
  destination:
    namespace: cla-test
    name: in-cluster
  project: infra-common
  source:
    path: common-applications/control/cla-test
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
