apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-etherpad
  namespace: argocd
  labels:
    community: os-infra
spec:
  destination:
    namespace: etherpad
    name: in-cluster
  project: infra-common
  source:
    path: common-applications/control/etherpad
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  ignoreDifferences:
    - jsonPointers:
        - /data
        - /metadata/labels
      kind: Secret
      name: ether-secret
      namespace: etherpad
