apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-grafana
  namespace: argocd
  labels:
    community: os-infra
  annotations:
    recipients.argocd-notifications.argoproj.io: email:tommylikehu@gmail.com
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infra-common
  source:
    path: common-applications/control/grafana
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
