apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-cn-north4-repo-download
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    community: mindspore-cn-north4
spec:
  destination:
    namespace: download
    name: cn-north-4-x86-external
  project: mindspore
  source:
    path: applications/repo-download-cn-north4
    repoURL: https://github.com/opensourceways/infra-mindspore.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
