apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-hk-x86-slave
  namespace: argocd
  labels:
    community: mindspore-hk
spec:
  destination:
    namespace: jenkins
    name: mindspore-hk-external
  project: mindspore
  source:
    path: applications/jenkins-x86-slave-hk
    repoURL: https://github.com/opensourceways/infra-mindspore.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
