apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-jenkins
  namespace: argocd
  labels:
    community: mindspore-cn-north1
spec:
  destination:
    namespace: jenkins
    name: mindspore-external
  project: mindspore
  source:
    path: applications/jenkins
    repoURL: https://github.com/opensourceways/infra-mindspore.git
    targetRevision: HEAD
