apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-cn-north4-newyear-events
  namespace: argocd
  labels:
    community: mindspore-cn-north4
spec:
  destination:
    namespace: summary
    name: cn-north-4-x86-external
  project: mindspore
  source:
    path: applications/newyear
    repoURL: https://github.com/opensourceways/infra-mindspore.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true