apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openlookeng-hk-fluentd
  namespace: argocd
  labels:
    community: openlookeng-hk
spec:
  destination:
    namespace: kube-system
    name: openlookeng-external
  project: infra-common
  source:
    path: common-applications/control/fluentd
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
