apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ascend-dailybuild
  namespace: argocd
  labels:
    community: pytorch
spec:
  destination:
    namespace: ascend-dailybuild
    name: pytorch-external
  project: pytorch
  source:
    path: applications/ascend-build
    repoURL: https://github.com/opensourceways/infra-pytorch.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false