apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch-jenkins
  namespace: argocd
  labels:
    community: pytorch
spec:
  destination:
    namespace: jenkins
    name: pytorch-external
  project: pytorch
  source:
    path: applications/jenkins
    repoURL: https://github.com/opensourceways/infra-pytorch.git
    targetRevision: HEAD
