apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch-officialrepo
  namespace: argocd
  labels:
    community: pytorch
spec:
  destination:
    namespace: officialrepo
    name: pytorch-external
  project: pytorch
  source:
    path: applications/officialrepo
    repoURL: https://github.com/opensourceways/infra-pytorch.git
    targetRevision: HEAD
