apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-cn-north4-fluentd
  namespace: argocd
  labels:
    community: openeuler-cn-north4
spec:
  destination:
    namespace: kube-system
    server: https://114.116.226.125:5443
  project: infra-common
  source:
    path: common-applications/control/fluentd
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/scope
        - /status
