apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openlookeng-jenkins
  namespace: argocd
  labels:
    community: openlookeng
spec:
  destination:
    namespace: jenkins
    name: openlookeng-external
  project: openlookeng
  source:
    path: applications/jenkins
    repoURL: https://github.com/opensourceways/infra-openlookeng.git
    targetRevision: HEAD

