apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openlookeng-repo
  namespace: argocd
  labels:
    community: openlookeng
spec:
  destination:
    namespace: repo
    name: openlookeng-external
  project: openlookeng
  source:
    path: applications/repo
    repoURL: https://github.com/opensourceways/infra-openlookeng.git
    targetRevision: HEAD
