apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openlookeng-website
  namespace: argocd
  labels:
    community: openlookeng
spec:
  destination:
    namespace: website
    server: https://159.138.57.217:5443 
  project: openlookeng
  source:
    path: applications/website
    repoURL: https://github.com/opensourceways/infra-openlookeng.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
