apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-common
  namespace: argocd
spec:
  description: The project that holds all of the common service used by different communities
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://159.138.41.5:5443
    - namespace: '*'
      server: https://114.116.226.125:5443
    - namespace: '*'
      server: https://159.138.57.217:5443
    - namespace: '*'
      server: https://119.8.45.34:5443
  sourceRepos:
    - https://github.com/opensourceways/infra-common.git

