apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-singapore-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    community: control-singapore
spec:
  destination:
    namespace: cert-manager
    server: https://119.8.174.163:5443
  project: infra-common
  source:
    path: common-applications/control/cert-manager
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
