apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-singapore-ingress
  namespace: argocd
  labels:
    community: control-singapore
spec:
  destination:
    namespace: ingress-nginx
    name: infra-singapore-x86-external
  project: infra-common
  source:
    path: common-applications/control/ingress-singapore
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
