apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-singapore-metric-server
  namespace: argocd
  labels:
    community: control-singapore
spec:
  destination:
    namespace: kube-system
    server: https://119.8.174.163:5443
  project: infra-common
  source:
    path: common-applications/control/metrics-server-x86
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
