apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-singapore-secret-manager
  namespace: argocd
  labels:
    community: control-singapore
spec:
  destination:
    namespace: secrets-manager
    server: https://119.8.174.163:5443
  project: infra-common
  source:
    path: common-applications/control/secret-manager
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/scope
        - /status
