apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch-cn-north4-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    community: pytorch-cn-north4
spec:
  destination:
    namespace: cert-manager
    name: pytorch-external
  project: infra-common
  source:
    path: common-applications/control/cert-manager
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
