apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch-cn-north4-ingress
  namespace: argocd
  labels:
    community: pytorch
spec:
  destination:
    namespace: ingress-nginx
    name: pytorch-external
  project: infra-common
  source:
    path: common-applications/pytorch/ingress
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
