apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: infra-common
  source:
    path: common-applications/control-vault
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true